### ISSUE TITLE
Website does not have the correct trademark disclaimer

### ISSUE THREAD

**Issue by thisisobate** [telepresenceio/telepresence.io#202]
As part of our ongoing effort to https://github.com/cncf/techdocs/issues/198, we noticed that the website does not pass the trademark criteria on [CLOMonitor](https://clomonitor.io/search?foundation=cncf&not_passing_check=trademark_disclaimer&page=1).

To fix this:
Head to the source code of the website. In the `<footer>` section, add a **disclaimer** or **link** to the Linux foundation trademark disclaimer page:

**Disclaimer**
```
<footer>
   <p>The Linux Foundation has registered trademarks and uses trademarks. For a list of trademarks of The Linux Foundation, 
         please see our <a href="https://www.linuxfoundation.org/legal/trademark-usage">Trademark Usage page</a>.
   </p>
</footer>
```

**Link**
```
 <footer>
      <ul>
          <li><a href="https://www.linuxfoundation.org/legal/trademark-usage">Trademarks</a></li>
      </ul>
 </footer>
```

**Comment by mariasalcedo** [comment]
This website does contain the disclaimer.
Apparently, CLOMonitor isn't able to verify it.

**Comment by khussey** [comment]
@mariasalcedo based on https://clomonitor.io/projects/cncf/telepresence#telepresence_legal it seems the CLOMonitor is in fact able to verify it?

**Comment by mariasalcedo** [comment]
@khussey I checked this morning and it was in red. Thanks for checking again!
@thisisobate If you agree, I think this issue can be closed for now since the requirement has been already fulfilled.

**Comment by thallgren** [comment]
Closing due to reporter not responding.
