### ISSUE TITLE
--http-match is not available

### ISSUE THREAD

**Issue by ilievmark** [telepresenceio/telepresence.io#205]
Hello

Please update if you have --http-match feature implemented for filtering intercepted traffic in current version
Like its described in here
https://github.com/telepresenceio/telepresence.io/blob/master/docs/pre-release/concepts/intercepts.md

I cant use it in current version

P.S. I can see its pre-release concept, but it also stands for 2.14.0 version, which is older

Thank you

**Comment by thallgren** [comment]
`--http-xxx` flags are not part of the OSS offering.
