### ISSUE TITLE
Create user tutorial for creating a personal intercept

### ISSUE THREAD

**Issue by efunk** [telepresenceio/telepresence.io#54]
We recently made some documentation improvements by changing the term "selective" intercepts to "personal" intercepts.

There is a request to add a simple tutorial(i.e. ~3 steps) to the "How do I..." section titled "Create a personal intercept" and include the animation that Brian has created.

**Comment by efunk** [comment]
Document changes mentioned in description handled here: https://github.com/telepresenceio/telepresence.io/pull/52

**Comment by LukeShu** [comment]
https://github.com/datawire/getambassador.io/pull/1163
https://github.com/telepresenceio/telepresence.io/pull/62

**Comment by efunk** [comment]
Resolved and published to our online documentation.
