### ISSUE TITLE
Improve user's first experience.

### ISSUE THREAD

**Issue by thallgren** [telepresenceio/telepresence.io#55]
We need to provide a very visible page that tells the user how to install telepresence in the cluster where we explain what happens the first time the user executes `telepresence connect` unless the traffic manager has been installed already. The page should outline the various ways of installing the traffic manager  using `telepresence connect` or a helm install that in turn may be global or namespace specific. The page must provide relevant links to our RBAC page.

The RBAC page must be updated so that it is easy to find the exact permissions needed to install the traffic manager.

I write "very visible" above, because several users have been confused about this, not finding relevant documentation. Some is there already, but spread out. Other documentation (like RBAC to install the traffic manager) is lacking.

**Comment by khussey** [comment]
This was addressed with the 2.4.5 release, see https://www.getambassador.io/docs/telepresence/latest/reference/rbac/#administrating-telepresence.
